name: Static Site CI
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  static-site:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy status site
        uses: upptime/uptime-monitor@master
        with:
          STATUS_WEBSITE_CI: "true"
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
